### ISSUE TITLE
Need help to implement pull down to refresh + pull up to loadmore

### ISSUE THREAD

**Issue by darklordqnct** [GDG-Korea/PinterestLikeAdapterView#17]
I am trying to implement pull up to load more in this library, creating new file base on MultiColumnPullToRefreshListView.java, it took me a lot of time. I am new in android and my experience is also very limited. Please help me to implement BOTH pull down to refresh and pull up to loadmore in your PLA library. Thank you very much.

**Comment by dalinaum** [comment]
Sorry. `MultiColumnPullToRefreshListView` is deprecated now. Using `SwipeRefreshLayout` is a better way.
