### ISSUE TITLE
Bug on Lollipop : initializeScrollbars is undefined

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [GDG-Korea/PinterestLikeAdapterView#31]
The function "initializeScrollbars" seems to be removed from View.java :
http://developer.android.com/reference/android/view/View.html

This means that "PLA_AbsListView.java" cannot use it anymore.

I've made a post about it on StackOverflow and also reported the missing information of it to Google:
http://stackoverflow.com/q/26448771
https://code.google.com/p/android/issues/detail?id=77745

Please fix this issue.

**Comment by dalinaum** [comment]
Fixed this probmel using an ad hoc patch. I will reimplement it later. Thanks for your report.
https://github.com/GDG-Korea/PinterestLikeAdapterView/commit/55a55dfb030f9eac6c8fa12fe1e3550482989564
