### ISSUE TITLE
Couldn't find the MultiColumnPullToRefreshListView class.

### ISSUE THREAD

**Issue by Guoqing-Wu** [GDG-Korea/PinterestLikeAdapterView#40]
In How to use, I find this:
To use pull-to-refresh features.
check this project as library project.
MultiColumnPullToRefreshListView class in extra folder is what you need.

But, I couldn't find the MultiColumnPullToRefreshListView class.

**Comment by dalinaum** [comment]
I'm sorry. MultiColumnPullToRefreshListView is obsolete now. If you really want to use this class, check old revisions please.

**Comment by usherdl** [comment]
Hope you can add MultiColumnPullToRefreshListView back soon .

**Comment by dalinaum** [comment]
Use `SwipeRefreshLayout` instead. It's a better way to implement pull to refresh.
